name: CI Pipeline (DOC1)

on:
  #Manually trigger workflow runs
  workflow_dispatch:
  #Trigger the workflow on push from the master/main branch
  push:
    branches: [master]

jobs:
  # Build job
  build:
    name: My First Pipeline
    runs-on:
      ubuntu-latest
      # Job's steps
    steps:
      # Check-out your repository
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo "Continuous Integration"
